/* Mocha is a test framework which we use to run all of these badboys
* while Chai is an expectation framework. So Mocha sets up and describes
* test suites and Chai provides the tools to perform assertions against
* the code */

var expect = require('chai');
    request = require('supertest');
// TODO: Remember to update this later
request = request('localhost:8080');


describe('When a user navigates to the page', function () {

    //First thing is that the server is running
    it("the page loads on the expected server", function (done) {
        // To do this GET the root then test it
        request.get('/')
            .expect(200, done);
    });

    // This is generated by script so it DEFINITELY needs a timeout
    it("the SVG script is loaded", function (done) {
        this.timeout(5000);
        request.get('/')
            .expect(/<svg/);
        done();
    });

    // TODO: decide the title of the website
    it("the title is displayed", function (done) {
        request.get('/')
            .expect(/<h1>Cocaine Map<\/h1>/, done);
    });

    it("a form with the id back-button displays", function (done) {
        request.get('/')
            .expect(/<form.*?id="back-button"[\s\S]*?<\/form>/, done);
    });

    it("a 'Key' is displayed to show how the colours relate to the data", function (done) {
        request.get('/')
            .expect(/<div.*?id="key"[\s\S]*?<\/div>/, done);
    });


    /* TODO: 
    -*      Test for countries getting coloured in +
    -*      Test for Retail price tab is active tab

    it("the retail price is pre-selected and wholesale price is available for selection", function (done) {
        request.get('/')
            .expect()
    });
    */


});
